// Runtime loader for the data-driven ICAO operator database generated by
// scripts/fetch-callsign-db.mjs (public/data/aircraft-operators.json).
// We do NOT hand-author callsign->operator mappings here; this parses the community
// Mictronics readsb operator dataset and resolves an operator by ICAO 3-letter prefix.

export type OperatorEntry = {
  name: string;
  country: string;
  telephony: string;
  military: boolean;
};

export type OperatorDb = Map<string, OperatorEntry>;

type RawOperator = { n?: string; c?: string; r?: string; m?: number };
type RawOperatorDbFile = { operators?: Record<string, RawOperator> };

export function parseOperatorDb(payload: unknown): OperatorDb {
  const db: OperatorDb = new Map();
  const operators = (payload as RawOperatorDbFile | null)?.operators;
  if (!operators || typeof operators !== 'object') return db;
  for (const [prefix, entry] of Object.entries(operators)) {
    if (!entry || typeof entry !== 'object') continue;
    const name = String(entry.n ?? '').trim();
    if (!name) continue;
    db.set(prefix.toUpperCase(), {
      name,
      country: String(entry.c ?? '').trim(),
      telephony: String(entry.r ?? '').trim(),
      military: entry.m === 1,
    });
  }
  return db;
}

export type OperatorMatch = { prefix: string; entry: OperatorEntry };

// Resolve by the leading 3-letter ICAO designator (e.g. "RCH431" -> "RCH").
// Registrations ("N123AB") and dynamic tactical callsigns ("DRAGON") that are not
// registered operator prefixes simply return null instead of a guessed mapping.
export function resolveOperator(callsign: string, db: OperatorDb): OperatorMatch | null {
  const alpha = callsign.trim().toUpperCase().match(/^[A-Z]+/)?.[0] ?? '';
  if (alpha.length < 3) return null;
  const prefix = alpha.slice(0, 3);
  const entry = db.get(prefix);
  return entry ? { prefix, entry } : null;
}
