import type { EvidenceItem, VerificationClaim } from './types';

type SeedEvidence = Omit<EvidenceItem, 'id' | 'claimId' | 'relatedIds'> & { relatedIds?: string[] };

export const demoClaims: VerificationClaim[] = [
  {
    id: 'claim-iran-f35-shootdown-2026',
    regionId: 'global',
    title: '이란이 미군 F-35 전투기를 격추했다는 전시 보도 주장',
    shortTitle: 'F-35 격추 주장',
    claimType: 'aircraft_shootdown',
    actor: '이란 국영·친정부권 보도/소셜 확산',
    targetAsset: '미군 F-35 전투기',
    claimedAt: '2026-04-03T10:00:00.000Z',
    createdAt: '2026-07-04T00:00:00.000Z',
    claimedLocation: { name: '중동 작전권역 공개 보도 범위', lat: 26.5, lon: 52.2 },
    timeWindowStart: '2026-04-03T04:00:00.000Z',
    timeWindowEnd: '2026-04-03T16:00:00.000Z',
    geoRadiusKm: 240,
    geoBufferKm: 45,
    claimSummary: '전시 정보전 상황에서 전투기 격추 주장이 보도·소셜 영상으로 확산됐다는 가정하에, 공개 보도·팩트체크·항적·위성 장면 메타데이터·열 이상 여부를 교차 검증합니다.',
    sourceUrls: [
      'https://www.cbsnews.com/live-updates/iran-war-us-trump-warns-more-coming-oil-gas-strait-hormuz/',
      'https://factcheck.afp.com/doc.afp.com.B2U99ZR',
      'https://www.boomlive.in/fact-check/viral-video-us-fighter-jets-abandoned-destroyed-f-35-iran-claim-fact-check-30904',
    ],
    keywords: ['F-35', 'shootdown', 'Iran', 'fighter jet', '격추', '전투기'],
    priority: 'warning',
  },
  {
    id: 'claim-kadiz-mass-entry',
    regionId: 'seoul-airspace',
    title: 'KADIZ 인근 군용기 대량 진입 보도 검증',
    shortTitle: 'KADIZ 대량 진입',
    claimType: 'airspace_closure',
    actor: '지역 안보 보도/소셜 확산',
    claimedAt: '2026-07-04T01:00:00.000Z',
    createdAt: '2026-07-04T00:00:00.000Z',
    claimedLocation: { name: '수도권·KADIZ 인근 공개 AOI', lat: 37.56, lon: 126.98 },
    timeWindowStart: '2026-07-04T00:00:00.000Z',
    timeWindowEnd: '2026-07-04T10:00:00.000Z',
    geoRadiusKm: 320,
    geoBufferKm: 60,
    claimSummary: 'KADIZ 또는 수도권 인근 공역 활동 급증 주장을 공개 ADS-B, NOTAM, FIR, 뉴스 보도와 함께 검증합니다.',
    sourceUrls: [],
    keywords: ['KADIZ', 'airspace', 'Korea', '항공기', '공역'],
    priority: 'watch',
  },
  {
    id: 'claim-scs-base-strike',
    regionId: 'south-china-sea',
    title: '남중국해 인공섬 기지 타격·피해 위성 확인 주장',
    shortTitle: '남중국해 기지 타격',
    claimType: 'base_strike',
    actor: '미확인 소셜/지역 매체',
    claimedAt: '2026-07-04T01:00:00.000Z',
    createdAt: '2026-07-04T00:00:00.000Z',
    claimedLocation: { name: '남중국해 공개 AOI', lat: 11.17, lon: 112.19 },
    timeWindowStart: '2026-07-04T00:00:00.000Z',
    timeWindowEnd: '2026-07-04T10:00:00.000Z',
    geoRadiusKm: 220,
    geoBufferKm: 50,
    claimSummary: '기지 피해 사진 또는 위성 확인 주장에 대해 Copernicus 장면 메타데이터, NASA FIRMS 열 이상, AIS/항공 활동, 뉴스 출처를 결합합니다.',
    sourceUrls: [],
    keywords: ['South China Sea', 'base strike', 'satellite image', 'Spratly', '기지', '위성'],
    priority: 'warning',
  },
  {
    id: 'claim-taiwan-strait-sortie-spike',
    regionId: 'taiwan-strait',
    title: '대만해협 항공 활동 급증 및 공역 긴장 주장',
    shortTitle: '대만해협 활동 급증',
    claimType: 'force_movement',
    actor: '지역 안보 보도/오픈소스 계정',
    claimedAt: '2026-07-04T01:00:00.000Z',
    createdAt: '2026-07-04T00:00:00.000Z',
    claimedLocation: { name: '대만해협 공개 AOI', lat: 24.49, lon: 119.61 },
    timeWindowStart: '2026-07-04T00:00:00.000Z',
    timeWindowEnd: '2026-07-04T10:00:00.000Z',
    geoRadiusKm: 260,
    geoBufferKm: 60,
    claimSummary: '공개 항적, 보도량, FIR/NOTAM, 위성 통과 가능성을 결합해 활동 급증 주장을 검증합니다.',
    sourceUrls: [],
    keywords: ['Taiwan Strait', 'sortie', 'aircraft', 'activity', '대만해협'],
    priority: 'watch',
  },
  {
    id: 'claim-west-sea-closure',
    regionId: 'west-sea-nll',
    title: '서해 NLL 인근 공역·해역 폐쇄 및 군사훈련 주장',
    shortTitle: '서해 폐쇄 주장',
    claimType: 'airspace_closure',
    actor: '지역 보도/소셜 확산',
    claimedAt: '2026-07-04T01:00:00.000Z',
    createdAt: '2026-07-04T00:00:00.000Z',
    claimedLocation: { name: '서해/NLL 공개 AOI', lat: 37.91, lon: 125.12 },
    timeWindowStart: '2026-07-04T00:00:00.000Z',
    timeWindowEnd: '2026-07-04T10:00:00.000Z',
    geoRadiusKm: 250,
    geoBufferKm: 55,
    claimSummary: '공개 NOTAM, AIS, 항적 공백, 참고 경계선, 뉴스 보도를 통해 폐쇄·훈련 주장의 공개 근거를 확인합니다.',
    sourceUrls: [],
    keywords: ['NLL', 'West Sea', 'NOTAM', 'exercise', '서해', '훈련'],
    priority: 'watch',
  },
];

export const demoClaimEvidence: Record<string, SeedEvidence[]> = {
  'claim-iran-f35-shootdown-2026': [
    {
      category: 'news',
      stance: 'context',
      title: '격추 주장이 보도 흐름에 등장',
      summary: '라이브 보도/전시 업데이트 맥락에서 격추 주장과 부인·검증 필요성이 함께 등장했습니다.',
      source: 'CBS News live updates',
      confidence: 0.66,
      observedAt: '2026-04-03T10:00:00.000Z',
      url: 'https://www.cbsnews.com/live-updates/iran-war-us-trump-warns-more-coming-oil-gas-strait-hormuz/',
    },
    {
      category: 'official',
      stance: 'contradicts',
      title: '공식 부인 보도가 확인됨',
      summary: '공개 보도상 미 당국/CENTCOM 계열 부인 내용이 함께 확인되어 격추 주장에 강한 반대 근거로 취급합니다.',
      source: 'Official denial reported in public news',
      confidence: 0.82,
      observedAt: '2026-04-03T11:30:00.000Z',
      url: 'https://www.cbsnews.com/live-updates/iran-war-us-trump-warns-more-coming-oil-gas-strait-hormuz/',
      caveat: '공식 발표는 링크 원문과 발표 시각을 분석관이 별도 확인해야 합니다.',
    },
    {
      category: 'factcheck',
      stance: 'contradicts',
      title: '격추 영상/이미지 조작 가능성 팩트체크',
      summary: '팩트체크 기관이 관련 영상의 생성형/조작 가능성 또는 맥락 불일치를 지적한 사례가 확인됩니다.',
      source: 'AFP Fact Check',
      confidence: 0.84,
      observedAt: '2026-04-03T12:00:00.000Z',
      url: 'https://factcheck.afp.com/doc.afp.com.B2U99ZR',
      caveat: '팩트체크가 특정 영상만 다뤘다면 전체 주장의 모든 근거를 자동 반박하는 것은 아닙니다.',
    },
    {
      category: 'factcheck',
      stance: 'contradicts',
      title: '파괴된 F-35 영상 재검증',
      summary: '관련 영상이 실제 격추 증거로 보기 어렵다는 공개 팩트체크가 존재합니다.',
      source: 'BOOM Fact Check',
      confidence: 0.8,
      observedAt: '2026-04-03T12:30:00.000Z',
      url: 'https://www.boomlive.in/fact-check/viral-video-us-fighter-jets-abandoned-destroyed-f-35-iran-claim-fact-check-30904',
    },
  ],
};

export function claimsForRegion(regionId: VerificationClaim['regionId']) {
  if (regionId === 'global') return demoClaims;
  return demoClaims.filter((claim) => claim.regionId === regionId || claim.id === 'claim-iran-f35-shootdown-2026');
}
